// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
import HTTPTypes
/// Paris metro, RER and bus network for the Via app.
public struct Client: APIProtocol {
    /// The underlying HTTP client.
    private let client: UniversalClient
    /// Creates a new client.
    /// - Parameters:
    ///   - serverURL: The server URL that the client connects to. Any server
    ///   URLs defined in the OpenAPI document are available as static methods
    ///   on the ``Servers`` type.
    ///   - configuration: A set of configuration values for the client.
    ///   - transport: A transport that performs HTTP operations.
    ///   - middlewares: A list of middlewares to call before the transport.
    public init(
        serverURL: Foundation.URL,
        configuration: Configuration = .init(),
        transport: any ClientTransport,
        middlewares: [any ClientMiddleware] = []
    ) {
        self.client = .init(
            serverURL: serverURL,
            configuration: configuration,
            transport: transport,
            middlewares: middlewares
        )
    }
    private var converter: Converter {
        client.converter
    }
    /// Prochains passages
    ///
    /// Prochains départs par ligne et destination pour une station, en temps réel (PRIM Île-de-France Mobilités) quand la source répond, sinon selon les horaires disponibles. `source` dit ce que les horodatages valent.
    ///
    /// - Remark: HTTP `GET /departures`.
    /// - Remark: Generated from `#/paths//departures/get(departures.forStation)`.
    public func departures_forStation(_ input: Operations.Departures_forStation.Input) async throws -> Operations.Departures_forStation.Output {
        try await client.send(
            input: input,
            forOperation: Operations.Departures_forStation.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/departures",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "stationId",
                    value: input.query.stationId
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.Departures_forStation.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Operations.Departures_forStation.Output.Ok.Body.JsonPayload.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Liveness probe
    ///
    /// Reports whether the API can reach Postgres.
    ///
    /// - Remark: HTTP `GET /health`.
    /// - Remark: Generated from `#/paths//health/get(health)`.
    public func health(_ input: Operations.Health.Input) async throws -> Operations.Health.Output {
        try await client.send(
            input: input,
            forOperation: Operations.Health.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/health",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.Health.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Operations.Health.Output.Ok.Body.JsonPayload.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Calculer des itinéraires
    ///
    /// Calcule plusieurs itinéraires depuis la position courante vers une station ou une adresse. Les horaires en direct restent réservés au panneau de départs de la station proche.
    ///
    /// - Remark: HTTP `GET /journeys`.
    /// - Remark: Generated from `#/paths//journeys/get(journeys.plan)`.
    public func journeys_plan(_ input: Operations.Journeys_plan.Input) async throws -> Operations.Journeys_plan.Output {
        try await client.send(
            input: input,
            forOperation: Operations.Journeys_plan.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/journeys",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .deepObject,
                    explode: true,
                    name: "origin",
                    value: input.query.origin
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .deepObject,
                    explode: true,
                    name: "destination",
                    value: input.query.destination
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "limit",
                    value: input.query.limit
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "requestedAt",
                    value: input.query.requestedAt
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "datetimeRepresents",
                    value: input.query.datetimeRepresents
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .deepObject,
                    explode: true,
                    name: "requiredModes",
                    value: input.query.requiredModes
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .deepObject,
                    explode: true,
                    name: "excludedModes",
                    value: input.query.excludedModes
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .deepObject,
                    explode: true,
                    name: "preferredModes",
                    value: input.query.preferredModes
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.Journeys_plan.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Operations.Journeys_plan.Output.Ok.Body.JsonPayload.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Comprendre et calculer un itinéraire en langage naturel
    ///
    /// Interprète une phrase française, clarifie les lieux ou le sens temporel si nécessaire, puis calcule un itinéraire vérifié.
    ///
    /// - Remark: HTTP `POST /natural-journeys`.
    /// - Remark: Generated from `#/paths//natural-journeys/post(naturalJourneys.submit)`.
    public func naturalJourneys_submit(_ input: Operations.NaturalJourneys_submit.Input) async throws -> Operations.NaturalJourneys_submit.Output {
        try await client.send(
            input: input,
            forOperation: Operations.NaturalJourneys_submit.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/natural-journeys",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .post
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                let body: OpenAPIRuntime.HTTPBody?
                switch input.body {
                case let .json(value):
                    body = try converter.setRequiredRequestBodyAsJSON(
                        value,
                        headerFields: &request.headerFields,
                        contentType: "application/json; charset=utf-8"
                    )
                }
                return (request, body)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.NaturalJourneys_submit.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Operations.NaturalJourneys_submit.Output.Ok.Body.JsonPayload.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Le réseau ferré visible
    ///
    /// Lignes de métro et de RER avec leurs polylignes et toutes leurs stations. La donnée ne change qu’à l’import GTFS — cache long. Les arrêts de bus se chargent par zone via `stationsInArea`.
    ///
    /// - Remark: HTTP `GET /network/rail-map`.
    /// - Remark: Generated from `#/paths//network/rail-map/get(network.railMap)`.
    public func network_railMap(_ input: Operations.Network_railMap.Input) async throws -> Operations.Network_railMap.Output {
        try await client.send(
            input: input,
            forOperation: Operations.Network_railMap.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/network/rail-map",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.Network_railMap.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Operations.Network_railMap.Output.Ok.Body.JsonPayload.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Les stations d’une zone
    ///
    /// Toutes les stations (bus compris) dans une petite boîte englobante, avec les badges des lignes qui les desservent. Pensé pour être appelé tuile par tuile pendant que la carte bouge : beaucoup de petites requêtes cachables plutôt qu’un seul payload énorme.
    ///
    /// - Remark: HTTP `GET /network/stations`.
    /// - Remark: Generated from `#/paths//network/stations/get(network.stationsInArea)`.
    public func network_stationsInArea(_ input: Operations.Network_stationsInArea.Input) async throws -> Operations.Network_stationsInArea.Output {
        try await client.send(
            input: input,
            forOperation: Operations.Network_stationsInArea.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/network/stations",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "minLatitude",
                    value: input.query.minLatitude
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "maxLatitude",
                    value: input.query.maxLatitude
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "minLongitude",
                    value: input.query.minLongitude
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "maxLongitude",
                    value: input.query.maxLongitude
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.Network_stationsInArea.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Operations.Network_stationsInArea.Output.Ok.Body.JsonPayload.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
    /// Recherche unifiée
    ///
    /// Arrêts de métro, RER et bus et adresses d’Île-de-France (géocodage BAN) en une seule liste classée. Avec une position, chaque résultat porte sa distance en mètres.
    ///
    /// - Remark: HTTP `GET /search`.
    /// - Remark: Generated from `#/paths//search/get(search.query)`.
    public func search_query(_ input: Operations.Search_query.Input) async throws -> Operations.Search_query.Output {
        try await client.send(
            input: input,
            forOperation: Operations.Search_query.id,
            serializer: { input in
                let path = try converter.renderedPath(
                    template: "/search",
                    parameters: []
                )
                var request: HTTPTypes.HTTPRequest = .init(
                    soar_path: path,
                    method: .get
                )
                suppressMutabilityWarning(&request)
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "q",
                    value: input.query.q
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "latitude",
                    value: input.query.latitude
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "longitude",
                    value: input.query.longitude
                )
                try converter.setQueryItemAsURI(
                    in: &request,
                    style: .form,
                    explode: true,
                    name: "limit",
                    value: input.query.limit
                )
                converter.setAcceptHeader(
                    in: &request.headerFields,
                    contentTypes: input.headers.accept
                )
                return (request, nil)
            },
            deserializer: { response, responseBody in
                switch response.status.code {
                case 200:
                    let contentType = converter.extractContentTypeIfPresent(in: response.headerFields)
                    let body: Operations.Search_query.Output.Ok.Body
                    let chosenContentType = try converter.bestContentType(
                        received: contentType,
                        options: [
                            "application/json"
                        ]
                    )
                    switch chosenContentType {
                    case "application/json":
                        body = try await converter.getResponseBodyAsJSON(
                            Operations.Search_query.Output.Ok.Body.JsonPayload.self,
                            from: responseBody,
                            transforming: { value in
                                .json(value)
                            }
                        )
                    default:
                        preconditionFailure("bestContentType chose an invalid content type.")
                    }
                    return .ok(.init(body: body))
                default:
                    return .undocumented(
                        statusCode: response.status.code,
                        .init(
                            headerFields: response.headerFields,
                            body: responseBody
                        )
                    )
                }
            }
        )
    }
}
